server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  maxHeaderBytes: "100KB"                     # 请求头大小限制，请求头包括客户端提交的Cookie数据，默认设置为100KB
  clientMaxBodySize: "200MB"                  # 客户端提交的Body大小限制，同时也影响文件上传大小，默认设置为200MB

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

path:
  audio: '/app/data/voice/'
  video: '/app/data/face2face/'
