version: '3.8'
networks:
  ai_network:
    driver: bridge

services:
  heygem-tts:
    image: registry.cn-hangzhou.aliyuncs.com/it00021hot/guiji2025_fish-speech-ziming
    container_name: heygem-tts
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ["0","1"]
              capabilities: ["gpu"]
              driver: "nvidia"
    ports:
      - '18180:8080'
    volumes:
      - /data/models/heygem/data/voice/data:/code/data
    command: /bin/bash -c "/opt/conda/envs/python310/bin/python3 tools/api_server.py --listen 0.0.0.0:8080"
    networks:
      - ai_network
  heygem-asr:
    image: registry.cn-hangzhou.aliyuncs.com/it00021hot/guiji2025_fun-asr
    container_name: heygem-asr
    restart: always
    privileged: true
    working_dir: /workspace/FunASR/runtime
    ports:
      - '10095:10095'
    command: sh /run.sh
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ["0","1"]
              capabilities: ["gpu"]
              driver: "nvidia"
    networks:
      - ai_network
  heygem-f2f:
    image: registry.cn-hangzhou.aliyuncs.com/it00021hot/guiji2025_heygem.ai
    container_name: heygem-f2f
    restart: always
    privileged: true
    volumes:
      - /data/models/heygem/data/face2face:/code/data
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ["0","1"]
              capabilities: ["gpu"]
              driver: "nvidia"
    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network
  heygem-file:
    image: registry.cn-hangzhou.aliyuncs.com/it00021hot/heygem-file:v0.0.2
    container_name: heygem-file
    restart: always
    privileged: true
    volumes:
      - /data/models/heygem/data/face2face:/app/data/face2face
      - /data/models/heygem/data/voice/data:/app/data/voice
    ports:
      - '8000:8000'
    networks:
      - ai_network
