
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  build:
    name: "heygem-file"                          # 编译后的可执行文件名称
    arch: "amd64"                           #不填默认当前系统架构，可选：386,amd64,arm,all
    system: "linux"                         #不填默认当前系统平台，可选：linux,darwin,windows,all
    mod: "none"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app